---

consul_debug: true

### Package
consul_version: "{{ lookup('env','CONSUL_VERSION') | default('1.2.0', true) }}"
consul_architecture_map:
  # this first entry seems redundant
  # (but it's required for reasons)
  amd64: amd64
  x86_64: amd64
  armv6l: arm
  armv7l: arm
  aarch64: arm64
  32-bit: "386"
  64-bit: amd64
consul_architecture: "{{ consul_architecture_map[ansible_architecture] }}"
consul_os: "{{ ansible_system | lower }}"
consul_pkg: "consul_{{ consul_version }}_{{ consul_os }}_{{ consul_architecture }}.zip"
consul_zip_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_{{ consul_os }}_{{ consul_architecture }}.zip"
consul_checksum_file_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version}}_SHA256SUMS"

### Install Method
consul_install_upgrade: false


packages_to_install:
  - git
  - unzip

### System user and group
consul_manage_user: yes
consul_user: "consul"
consul_manage_group: no
consul_group: "bin"

### Log user, group, facility
syslog_user: "{{ lookup('env','SYSLOG_USER') | default('root', true) }}"
syslog_group: "{{ lookup('env','SYSLOG_GROUP') | default('adm', true) }}"
consul_log_level: "{{ lookup('env','CONSUL_LOG_LEVEL') | default('INFO', true) }}"
consul_syslog_enable: "{{ lookup('env','CONSUL_SYSLOG_ENABLE') | default(true, true) }}"
consul_syslog_facility: "{{ lookup('env','CONSUL_SYSLOG_FACILITY') | default('local0', true) }}"


### Paths
consul_bin_path: "/usr/local/bin"
consul_config_path: "/etc/consul"
consul_configd_path: "{{ consul_config_path }}/consul.d"
consul_data_path: "/var/consul"
consul_log_path: "{{ lookup('env','CONSUL_LOG_PATH') | default('/var/log/consul', true) }}"
consul_run_path: "/var/run/consul"
consul_binary: "{{ consul_bin_path }}/consul"
consul_tls_path: "{{ lookup('env','CONSUL_TLS_DIR') | default('/etc/consul/ssl', true) }}"


consul_bootstrap_state: "{{ consul_config_path }}/.consul_bootstrapped"
consul_log_file: "{{ lookup('env','CONSUL_LOG_FILE') | default('consul.log', true) }}"
consul_tls_ca_crt: "consul-ca.pem"
consul_tls_server_crt: "server.pem"
consul_server_key: "server-key.pem"

### Ports
consul_ports_https: '8443'
consul_ports:
  dns: "{{ consul_ports_dns | default('8600', true) }}"
  http: "{{ consul_ports_http | default('8500', true) }}"
  https: "{{ consul_ports_https | default('8443', true) }}"
  rpc: "{{ consul_ports_rpc | default('8400', true) }}"
  serf_lan: "{{ consul_ports_serf_lan | default('8301', true) }}"
  serf_wan: "{{ consul_ports_serf_wan | default('8302', true) }}"
  server: "{{ consul_ports_server | default('8300', true) }}"

### This Server
consul_bind_address: "{{ lookup('env','CONSUL_BIND_ADDRESS') | default(hostvars[inventory_hostname]['consul_bind_address'], true) }}"
consul_advertise_address: "{{ lookup('env','CONSUL_ADVERTISE_ADDRESS') | default(hostvars[inventory_hostname]['consul_advertise_address'], true) }}"

### Servers
consul_group_name: "{{ lookup('env','CONSUL_GROUP_NAME') | default('consul_servers_dc1', true) }}"
consul_join: []
consul_join_wan: []
consul_servers: "\
  {% set _consul_servers = [] %}\
  {% for host in groups[consul_group_name] %}\
    {% set _consul_node_role = hostvars[host]['consul_node_role'] | default('client', true) %}\
    {% if ( _consul_node_role == 'server' or _consul_node_role == 'bootstrap') %}\
      {% if _consul_servers.append(host) %}{% endif %}\
    {% endif %}\
  {% endfor %}\
  {{ _consul_servers }}"

consul_lan_servers: "\
  {% set _consul_lan_servers = [] %}\
  {% for server in consul_servers %}\
    {% set _consul_datacenter = hostvars[server]['consul_datacenter'] | default('dc1', true) %}\
    {% if _consul_datacenter == consul_datacenter %}\
      {% if _consul_lan_servers.append(server) %}{% endif %}\
    {% endif %}\
  {% endfor %}\
  {{ _consul_lan_servers }}"
consul_lan_servercount: "{{ (consul_lan_servers | length) + (consul_join | length) }}"

# TLS
consul_tls_src_files: "{{ lookup('env','CONSUL_TLS_SRC_FILES') | default(role_path+'/files/tls', true) }}"
consul_tls_verify_incoming: false
consul_tls_verify_outgoing: true
consul_tls_verify_server_hostname: false
consul_tls_files_remote_src: no
